### ISSUE TITLE
Specify License of Files / Images

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-artwork#17]
A license file should be added to the repository to specify the licensing of the nixos images, logo, files, etc.

Example: Can I use these files to make my own stickers? Put it on pamphlets? etc.

**Comment by samueldr** [comment]
I have sourced the attributions and licenses as best as I could in #24, going forward, it would be best if this repository *did* have an actual license for the artwork (other than the logo).

* * *

## Priort art

 * OpenSUSE *[License All content in is licensed under CC-BY-SA 3.0 unless otherwise stated](https://github.com/openSUSE/artwork/blob/master/README.md)*
 * Debian [Doesn't specify a preferred license](https://wiki.debian.org/DebianDesktop/Artwork/Requirements)
 * Ubuntu *[Documents a couple licenses preferred](https://wiki.ubuntu.com/Artwork/Documentation/Licensing)*

**Comment by samueldr** [comment]
Tracked under #23; closing in favor of finishing this in #23.
