### ISSUE TITLE
Square logo?

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixos-artwork#42]
I was surprised that the logo is very close to square but it is not square. Is this intentional? Would a logo revision that makes it square be welcome?

**Comment by samueldr** [comment]
Can a regular hexagon be square? Maths says no! :)

Though, what do you mean, you want to see a logo file where the drawing area is square, with the logo appropriately centered?

What would be the use of such file? (It would help to know how it'd be used, I guess)

**Comment by ryantm** [comment]
Yes, I was looking for the drawing area to be square.

I am trying to fix this warning message that Discourse keeps warning us about:
![discourse_icon_warning](https://user-images.githubusercontent.com/4804/52902713-773a2e80-31c9-11e9-932e-4e0d646fc403.png)

It is asking for a 512x512 px logo.

**Comment by ryantm** [comment]
Well, I went ahead and extended the canvas in GIMP and uploaded it. It's weird that the icon directory Makefile generates a folder called 512x512, but the file inside is not that exact dimensions. Is that typical with icons?

**Comment by samueldr** [comment]
Oh, I would assume it's not "right" to have a 512x512 (or 𝒙×𝒙) directory with non-squared images. Keep this open, with actionable task: *make the Makefile generate square files*.

I believe this is how the png images are generated for use on an installed NixOS system, good thing that apparently nothing fails when using non-square images here.

**Comment by alyaeanyx** [comment]
It does seem like the logo being non-square causes it to be unevenly rescaled on GNOME:
![image](https://user-images.githubusercontent.com/74795488/160290997-a622bb2a-066a-435e-b97b-5385b3941078.png)
This is because the .svg is directly copied over into `hicolor/scalable/apps/` alongside the converted .png versions. Perhaps we should consider either making the SVG square or converting it into a square one in `icons/Makefile`.

Sorry for unearthing this issue after three years by the way :sweat_smile:

**Comment by samueldr** [comment]
Don't be sorry, you're right. This isn't looking correct :)

**Comment by OPNA2608** [comment]
I've found *a* way to do this fully at build time, would appreciate any opinions on it: #118
