### ISSUE TITLE
minify logo svg in nix-snowflake.svg

### ISSUE THREAD

**Issue by milahu** [NixOS/nixos-artwork#71]
expected: 1 KByte @ https://www.vectorlogo.zone/logos/nixos/nixos-icon.svg

actual: 26 KByte @ https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg

inkscape svg is very verbose

**Comment by samueldr** [comment]
The SVG files here are *source documents*, they include the "very verbose" inkscape stuff because it's used for authoring. E.g. there are elements to help align the logo with correct distances from text elements. Or hidden variants of the logo (flat colours vs. shaded).

If you need a minified SVG, either minify a copy where you need it, or use a build step that minifies as needed.

(more of a general note for other contributors, not aimed at you specifically) Merging similar changes would be a net loss for further authoring tasks. Not unlike deciding to minify comments and formatting out of a codebase.

**Comment by samueldr** [comment]
I'd even go as far as saying inkscape really should save files as `.svgi` or something like that to better cement the fact that the documents are "special" :).

**Comment by milahu** [comment]
can we haz both in one repo?

similar to the `src` &rarr; `dist` folders
